from dotenv import load_dotenv
from pydantic_settings import BaseSettings

load_dotenv()


class Config(BaseSettings):
    PROJECT_NAME: str = ...
    USER_LOGIN: str = ...
    USER_PASSWORD: str = ...
    CORS_ORIGINS: list[str] = ...
    CORS_ALLOW_CREDENTIALS: bool = ...
    CORS_ALLOW_METHODS: list[str] = ...
    CORS_ALLOW_HEADERS: list[str] = ...


def get_config() -> Config:
    return Config()


config = get_config()
